using Content.Shared.Verbs;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.InteractionHint.Widgets;

[GenerateTypedNameReferences]
public sealed partial class HintGui : UIWidget
{
    private readonly HintUiController _hintController;

    public void UpdateHints(EntityUid? worldTarget, EntityUid? handTarget)
    {
        var text = "";

        if (worldTarget != null)
        {
            text += HintTextIfVerb(_hintController.GetVerb(worldTarget, HintUiController.VerbType.Activate), "E");
            text += HintTextIfVerb(_hintController.GetVerb(worldTarget, HintUiController.VerbType.AltActivate), "ALT + E");
            text += HintTextIfVerb(_hintController.GetVerb(worldTarget, HintUiController.VerbType.Interact), "LEFT-CLICK");
        }

        if (handTarget != null)
        {
            text += HintTextIfVerb(_hintController.GetVerb(handTarget, HintUiController.VerbType.Activate), "Z");
            text += HintTextIfVerb(_hintController.GetVerb(handTarget, HintUiController.VerbType.AltActivate), "ALT + Z");
        }

        Interactions.Text = text;
    }

    public HintGui()
    {
        RobustXamlLoader.Load(this);

        _hintController = UserInterfaceManager.GetUIController<HintUiController>();
    }

    private string HintTextIfVerb(Verb? verb, string bind)
    {
        if (verb == null)
            return "";

        return bind + " - " + verb.Text + "\n";
    }
}
