using System.Linq;
using Content.Shared.Verbs;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.InteractionHint.Widgets;

[GenerateTypedNameReferences]
public sealed partial class HintGui : UIWidget
{
    private readonly HintUiController _hintController;

    public HintGui()
    {
        RobustXamlLoader.Load(this);

        _hintController = UserInterfaceManager.GetUIController<HintUiController>();
    }

    public void UpdateHints(EntityUid? target)
    {
        Interactions.Text = _hintController.GetAlternativeVerb(target)?.Text;
    }
}
